var serverurl = window.location.href;
serverurl = serverurl.substring(0, serverurl.lastIndexOf('/'));
var icm_server_addr = serverurl + "/tmpdata/";
var dbrowser = new Browser({
    chr:          '22',
    viewStart:    30010000,
    viewEnd:      30020000,
    cookieKey:    'human-grc_h38',
    //noZoomSlider: true,
    useFetchWorkers: false,
    pageName:     'dalliance-1',
    coordSystem: {
        speciesName: 'Human',
        taxon: 9606,
        auth: ' ',
        version: ' ',
        ucscName: 'hg38',
    },
    sources:     [{name:                 'Genome',
                       twoBitURI:            'http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit',
                       tier_type: 'sequence'},
                   {name: 'GENCODE',
                       desc: 'Gene structures from GENCODE 21',
                       bwgURI: '//www.biodalliance.org/datasets/GRCh38/gencode.v21.annotation.bb',
                       stylesheet_uri: '//www.biodalliance.org/stylesheets/gencode2.xml',
                       collapseSuperGroups: true,
                       trixURI: '//www.biodalliance.org/datasets/GRCh38/gencode.v21.annotation.ix'},
                   {name: 'Roll', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Roll.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Slide', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Slide.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Twist', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Twist.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Rise', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Rise.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Shift', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Shift.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Tilt', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Tilt.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Energy', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "E.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Nucleosomes', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Positions.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   
                 ],

    uiPrefix: '//www.biodalliance.org/release-0.13/',
    maxWorkers: 0,

    setDocumentTitle: false,
    disablePoweredBy: true,
    noTitle: false,
    hubs: ['http://ngs.sanger.ac.uk/production/ensembl/regulation/hub.txt', 'http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/hub.txt']
});