var serverurl = window.location.href;
serverurl = serverurl.substring(0, serverurl.lastIndexOf('/'));
var icm_server_addr = serverurl + "/tmpdata/";

var dbrowser = new Browser({
    chr:          '22',
    viewStart:    30010000,
    viewEnd:      30020000,
    cookieKey:    'human-grc_h37-fp',
    //noZoomSlider: true,
    useFetchWorkers: false,

    pageName:     'dalliance-1',

    coordSystem: {
        speciesName: 'Human',
        taxon: 9606,
        auth: ' ',
        version: ' ',
        ucscName: 'hg19',
    },
    

    sources:     [{name:                 'Genome',
                   twoBitURI:            'http://www.biodalliance.org/datasets/hg19.2bit',
                   tier_type:            'sequence',
                   provides_entrypoints: true,
                   pinned: true
                  },
                  {name: 'Genes',disabled:false,
                       desc: 'Gene structures from GENCODE 19',
                       bwgURI: '//www.biodalliance.org/datasets/gencode.bb',
                       stylesheet_uri: '//www.biodalliance.org/stylesheets/gencode.xml',
                       collapseSuperGroups: true,
                       trixURI: '//www.biodalliance.org/datasets/geneIndex.ix'},

                       {name: 'DNase I', desc: 'GM12878 DNaseI signals from UW', 
                        pennant: '//genome.ucsc.edu/images/encodeThumbnail.jpg', 
                        bwgURI: '//www.biodalliance.org/datasets/encode/wgEncodeUwDnaseGm12878Aln_2Reps.norm5.rawsignal.bw', 
                        style: [{type: 'default', style: {glyph: 'HISTOGRAM', BGCOLOR: 'rgb(8,104,172)', HEIGHT: 30, id: 'style1'}}], 
                        noDownsample: true},
                      {name: 'H3K4me1', disabled: true, desc: 'GM12878 H3K4me1 signal from Broad',
                       pennant: '//genome.ucsc.edu/images/encodeThumbnail.jpg',
                       bwgURI: '//www.biodalliance.org/datasets/encode/wgEncodeBroadHistoneGm12878H3k4me1StdAln_2Reps.norm5.rawsignal.bw',
                       style: [{type: 'default', style: {glyph: 'HISTOGRAM', BGCOLOR: 'rgb(166,71,71)', HEIGHT: 30, id: 'style1'}}], 
                       noDownsample: true}, 
                      {name: 'H3K4me2', disabled:true, desc: 'GM12878 H3K4me2 signal from Broad', 
                       pennant: '//genome.ucsc.edu/images/encodeThumbnail.jpg', 
                       bwgURI: '//www.biodalliance.org/datasets/encode/wgEncodeBroadHistoneGm12878H3k4me2StdAln_2Reps.norm5.rawsignal.bw', 
                       style: [{type: 'default', style: {glyph: 'HISTOGRAM', BGCOLOR: 'rgb(166,71,71)', HEIGHT: 30, id: 'style1'}}], 
                       noDownsample: true}, 
                      {name: 'H3K4me3', disabled:true, desc: 'GM12878 H3K4me3 signal from UW', 
                       pennant: '//genome.ucsc.edu/images/encodeThumbnail.jpg',
                       bwgURI: '//www.biodalliance.org/datasets/encode/wgEncodeUwHistoneGm12878H3k4me3StdAln_2Reps.norm5.rawsignal.bw',
                       style: [{type: 'default', style: {glyph: 'HISTOGRAM', BGCOLOR: 'rgb(166,71,71)', HEIGHT: 30, id: 'style1'}}], 
                       noDownsample: true}, 
                      {name: 'GM12878 ChromHMM', disabled:true, desc: 'GM12878 ChromHMM Genome Segmentation', 
                       pennant: '//genome.ucsc.edu/images/encodeThumbnail.jpg',
                       bwgURI: '//www.biodalliance.org/datasets/encode/gm12878.ChromHMM.bb',
                       style: [{type: 'bigbed', style: {glyph: 'BOX', FGCOLOR: 'black', BGCOLOR: 'blue', HEIGHT: 8, BUMP: false, LABEL: false, ZINDEX: 20, BGITEM: true, id: 'style1'}}, 
                              {type: 'bb-translation', style: {glyph: 'BOX', FGCOLOR: 'black', BGITEM: true, BGCOLOR: 'red', HEIGHT: 10, BUMP: true, ZINDEX: 20, id: 'style2'}}, 
                              {type: 'bb-transcript', style: {glyph: 'BOX', FGCOLOR: 'black', BGCOLOR: 'white', HEIGHT: 10, ZINDEX: 10, BUMP: true, LABEL: true, id: 'style3'}}]},
                       //http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeSydhNsome/wgEncodeSydhNsomeGm12878Sig.bigWig
                   {name: 'Roll', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Roll.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Slide', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Slide.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Twist', group: "Modeling-data", disabled: false, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Twist.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Rise', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Rise.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Shift', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Shift.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Tilt', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Tilt.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Energy', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "E.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                   {name: 'Nucleosomes', group: "Modeling-data", disabled: true, desc: 'TmBLab Wig',
                          pennant: 'http://genome.ucsc.edu/images/encodeThumbnail.jpg',
                          bwgURI: icm_server_addr + "Positions.bw",
                          style: [{type: 'bigwig', style: {glyph: 'LINEPLOT', BGCOLOR: '#ea115', FGCOLOR: 'green', HEIGHT: 40, id: 'style1'}}], 
                          noDownsample: true},
                          
                   
                 ],

    uiPrefix: '//www.biodalliance.org/release-0.13/',
    maxWorkers: 0,

    setDocumentTitle: false,
    disablePoweredBy: true,
    noTitle: false,
    hubs: ['http://ngs.sanger.ac.uk/production/ensembl/regulation/hub.txt', 'http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/hub.txt']
});